#!/bin/sh
MONITORDIR="/var/log/httpd"
inotifywait -m -r -e create,modify,open,close_write --format '%w%f' "${MONITORDIR}" | while read NEWFILE
do
        echo "File ${NEWFILE} has been updated" >> /tmp/updateme
done
