#!/bin/sh
MONITORDIR="/opt/SYMCScan/log"
inotifywait -m -r -e create,modify,open,close_write --format '%w%f' "${MONITORDIR}" | while read NEWFILE
do
        echo "File ${NEWFILE} has been updated" >> /tmp/updateme
        # Do we need to include epoch `date +%s`?
        /opt/SYMCScan/bin/logconverter –c ${NEWFILE} > /opt/SYMCScan/LogsToSplunk/${NEWFILE}
done
